menu:
  demo: http://demo.wuyuying.com/
  archive: /archives/
  About: /about.html

widgets:
- category
- tag
- search

copyright_start: 2014

excerpt_link: Read More

skip_render: node_modules/*

# GOOGLE ANALYTICS
ga: UA-74424222-1